spring:
  mvc:
    view:
      prefix: /WEB-INF/sources/jsp/
      suffix: .jsp

  datasource:
    # MARIADB
    #driverClassName: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC

    # MYSQL
    # 기본
    # driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC
    # username: root
    # password: root

    # MYSQL
    # log4j, Hikari 응용
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC

    # Hikari
    hikari.username: root
    hikari.password: root
    hikari.maximum-pool-size: 10
    hikari.connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
